### ISSUE TITLE
pixi not found

### ISSUE THREAD

**Issue by tibuch** [pavelzw/pixi-pycharm#16]
## Description

I want to configure PyCharm to use pixi, but it can not find pixi-pycharm can not find pixi.

My pixi installation is not in the default but in `/home/tibuch/Apps/pixi/bin/pixi`.

## Versions

```bash
❯ pixi --version
pixi 0.19.1

❯ pixi list | grep pixi-pycharm
pixi-pycharm               0.0.5         unix_1234567_0       8.6 KiB    conda  pixi-pycharm-0.0.5-unix_1234567_0.conda
```

PyCharm version: PyCharm 2023.2.3 (Community Edition)

Platform: linux-64

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Traceback (most recent call last):
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 149, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 123, in main
    conda_info_envs_json()
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 68, in conda_info_envs_json
    "envs": pixi_envs(),
            ^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 46, in pixi_envs
    platform = pixi_json(["info", *std_pixi_args()])["platform"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 42, in pixi_json
    return json.loads(pixi([*cmd, "--json"]))
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/libexec/conda", line 22, in pixi
    out = subprocess.check_output(["pixi", *cmd])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/tibuch/Gitrepos/repo-name/.pixi/envs/default/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixi'
```

**Comment by pavelzw** [comment]
> My pixi installation is not in the default but in `/home/tibuch/Apps/pixi/bin/pixi`.

Is `/home/tibuch/Apps/pixi/bin` on `PATH`?

**Comment by pavelzw** [comment]
That probably depends on your linux variant.
You could try to create a symlink for `pixi` on `/usr/local/bin` that points to `/home/tibuch/Apps/pixi/bin/pixi`. `/usr/local/bin` should definitely be on your PATH.
