### ISSUE TITLE
PyCharms throws the error message cannot invoke "com.jetbrains.python.sdk.flavors.conda.conda info json.getenv()" because "info" is null

### ISSUE THREAD

**Issue by JensBosch** [pavelzw/pixi-pycharm#19]
## Description

PyCharms throws the error message cannot invoke "com.jetbrains.python.sdk.flavors.conda.conda info json.getenv()" because "info" is null when I try to use the .pixi/envs/default/libexec/conda as the conda executable in PyCharm

## Versions

```bash
❯ pixi --version
0.22.0
❯ pixi list | grep pixi-pycharm
0.0.5
```

PyCharm version: Build #PY-241.15989.155

Platform: Ubuntu 22.04 LTS

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Traceback (most recent call last):
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 149, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 123, in main
    conda_info_envs_json()
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 68, in conda_info_envs_json
    "envs": pixi_envs(),
            ^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 46, in pixi_envs
    platform = pixi_json(["info", *std_pixi_args()])["platform"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 42, in pixi_json
    return json.loads(pixi([*cmd, "--json"]))
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/libexec/conda", line 22, in pixi
    out = subprocess.check_output(["pixi", *cmd])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/jens101010/PycharmProjects/MLG_SS24/.pixi/envs/default/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixi'
```

**Comment by pavelzw** [comment]
This looks like the same issue as #16.

Could you try installing pixi in `/usr/local/bin/pixi`?
