### ISSUE TITLE
Can not add conda executable in pycharm-ce

### ISSUE THREAD

**Issue by Zhou-Jiangcheng** [pavelzw/pixi-pycharm#29]
## Description

Can not add conda executable in pycharm-ce.
Already did everything described in README.
![Screenshot_20240728_192047](https://github.com/user-attachments/assets/c1ce45fc-7a31-454e-9b5b-b919be3e46ab)

## Versions

```bash
❯ pixi --version
pixi 0.26.1
❯ pixi list | grep pixi-pycharm
pixi-pycharm                          0.0.6      unix_1234567_0         8.6 KiB    conda  pixi-pycharm-0.0.6-unix_1234567_0.conda
```

PyCharm version: PyCharm 2024.1.4 (Community Edition)
PC-241.18034.82，2024年6月25日 构建
17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.

Platform: Debian 12
Linux zjc-office 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
## Logs

```
Attempting to run: ['info', '--envs', '--json']
Traceback (most recent call last):
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 165, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 139, in main
    conda_info_envs_json()
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 79, in conda_info_envs_json
    "envs": pixi_envs(),
            ^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 57, in pixi_envs
    platform = pixi_json(["info", *std_pixi_args()])["platform"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 53, in pixi_json
    return json.loads(pixi([*cmd, "--json"]))
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/libexec/conda", line 22, in pixi
    out = subprocess.check_output(["pixi", *cmd])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/zjc/python_works/seiser_pixi/.pixi/envs/default/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixi'
```

**Comment by pavelzw** [comment]
https://github.com/pavelzw/pixi-pycharm/issues/16#issuecomment-2066359437 might fix this. Where is your pixi installed? If it's in `~/.pixi/bin/pixi`, #20 is the issue which I should fix at some point.

**Comment by Zhou-Jiangcheng** [comment]
> [#16 (comment)](https://github.com/pavelzw/pixi-pycharm/issues/16#issuecomment-2066359437) might fix this. Where is your pixi installed? If it's in `~/.pixi/bin/pixi`, #20 is the issue which I should fix at some point.

Thank you very much! I found the solution works in #16 , I installed as default in ~/.pixi. Sorry to bother you, have a nice day.
