### ISSUE TITLE
Environment detection and setup fail

### ISSUE THREAD

**Issue by leroyvn** [pavelzw/pixi-pycharm#41]
## Description

When I try to add a Pixi environment to my PyCharm setup, detection goes well, but environment addition fails silently. I checked PyCharm logs and got the following stack trace:

```
com.intellij.execution.processTools.ProcessExistedNotZeroException: Error code: 1. Traceback (most recent call last):
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 178, in <module>
    sys.exit(main(args))
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 120, in conda_run
    os.execlp(
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 557, in execlp
    execvp(file, args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```
The corresponding failing lines in the `conda` script are:
```python
    os.execlp(
        "pixi",
        "pixi",
        "run",
        *std_pixi_args(),
        *pixi_env_cli_params(env),
        *pixi_run_args,
    )
```

I can execute the `conda` script from a terminal.

## Versions

```bash
❯ pixi --version
pixi 0.32.0
❯ pixi list | grep pixi-pycharm
pixi-pycharm                   0.0.7                unix_1234567_0       8.6 KiB     conda  pixi-pycharm-0.0.7-unix_1234567_0.conda
```

PyCharm version: PyCharm 2024.2.3 (Community Edition)
```
Build #PC-242.23339.19, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-45-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.23339.18)
  com.intellij.plugins.watcher (242.20224.155)
  com.andrey4623.rainbowcsv (2.0.2)
  com.github.weisj.darkmode (1.8.4-2024.2)
  cc.gmem.darkubuntutheme (1.4)
  me.lensvol.blackconnect (0.6.2)
  com.nasller.CodeGlancePro (1.9.1)
  com.intellij.plugins.macoskeymap (241.13688.16)
  com.intellij.plugins.vscodekeymap (242.20224.385)
  name.kropp.intellij.makefile (242.20224.155)
  com.jetbrains.space (242.23339.11)
  com.intellij.plugins.gnomekeymap (213.4250.391)
  com.leinardi.pycharm.mypy (0.16.3)
  com.fapiko.jetbrains.plugins.better_direnv (1.2.2)
  com.koxudaxi.ruff (0.0.39)
  nl.rubensten.texifyidea (0.9.7)
  com.dsoftware.ghtoolbar (2024.2.12)
  zielu.gittoolbox (600.0.1+242)
  mobi.hsz.idea.gitignore (4.5.3)
  com.brandiico.jetbrains-nightfall-theme (2.0.2)
Current Desktop: ubuntu:GNOME
```

Platform: Ubuntu 24.04

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['run', '-n', 'dev', '--no-capture-output', 'python', '-c', 'import sys; print(sys.executable)']
Traceback (most recent call last):
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 178, in <module>
    sys.exit(main(args))
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 156, in main
    conda_run(args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/libexec/conda", line 120, in conda_run
    os.execlp(
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 557, in execlp
    execvp(file, args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/home/leroyv/Documents/src/rayference/eradiate/.pixi/envs/dev/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by pavelzw** [comment]
where is your pixi installed (i.e. what's the output of `which pixi`)?

**Comment by pavelzw** [comment]
but it looks like i didn't fully fix #20

**Comment by leroyvn** [comment]
Hi @pavelzw, thanks for you very quick reply. My `pixi` executable location:
```
/home/leroyv/.pixi/bin/pixi
```

**Comment by leroyvn** [comment]
FWIW, I also manually executed
```
.pixi/envs/default/libexec/conda self-check
```
and got no error. So my assumption would be that the problem is within PyCharm itself.

**Comment by leroyvn** [comment]
I think I managed to fix this. Shall I create a PR?

**Comment by pavelzw** [comment]
sure :)
